places = ['Tokyo', 'Berlin', 'Malta', 'Maldives', 'New York']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)

print(f"I have mentioned {len(places)} places to visit.")